//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tjc.Modules.ExitSurvey.Admin
{
    public partial class ResponseDetail
    {
        protected global::System.Web.UI.WebControls.PlaceHolder plhMessage;
        protected global::System.Web.UI.WebControls.HyperLink lnkBack;
        protected global::System.Web.UI.WebControls.Panel pnlDetail;
        protected global::System.Web.UI.WebControls.Literal ltSubmitted;
        protected global::System.Web.UI.WebControls.Literal ltSubmittedBy;
        protected global::System.Web.UI.WebControls.Literal ltShare;
        protected global::System.Web.UI.WebControls.Repeater rptGeneral;
        protected global::System.Web.UI.WebControls.Literal ltQ1Other;
        protected global::System.Web.UI.WebControls.Literal ltQ2;
        protected global::System.Web.UI.WebControls.Literal ltQ3;
        protected global::System.Web.UI.WebControls.Literal ltQ4;
        protected global::System.Web.UI.WebControls.Repeater rptReasons;
        protected global::System.Web.UI.WebControls.Literal ltQ5Other;
        protected global::System.Web.UI.WebControls.Repeater rptSupervision;
        protected global::System.Web.UI.WebControls.Literal ltQ7;
        protected global::System.Web.UI.WebControls.Literal ltQ8;
        protected global::System.Web.UI.WebControls.Literal ltQ9;
        protected global::System.Web.UI.WebControls.Literal ltName;
        protected global::System.Web.UI.WebControls.Literal ltPositionTitle;
        protected global::System.Web.UI.WebControls.Literal ltSupervisorName;
        protected global::System.Web.UI.WebControls.Literal ltSupervisorTitle;
        protected global::System.Web.UI.WebControls.Literal ltHired;
        protected global::System.Web.UI.WebControls.Literal ltSeparated;
        protected global::System.Web.UI.WebControls.Literal ltDateCompleted;
    }
}
