//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tjc.Modules.Arbitrators.Views
{


    public partial class Detail
    {

        protected global::System.Web.UI.WebControls.Panel pnlNotFound;

        protected global::System.Web.UI.WebControls.HyperLink lnkNotFoundBack;

        protected global::System.Web.UI.WebControls.Panel pnlApplication;

        protected global::System.Web.UI.WebControls.Literal ltHeading;

        protected global::System.Web.UI.WebControls.Literal ltAddress;

        protected global::System.Web.UI.WebControls.Literal ltPhone;

        protected global::System.Web.UI.WebControls.HyperLink lnkEmail;

        protected global::System.Web.UI.WebControls.Literal ltWebsite;

        protected global::System.Web.UI.WebControls.Literal ltPreferredAreas;

        protected global::System.Web.UI.WebControls.CheckBox chkBarMember;

        protected global::System.Web.UI.WebControls.CheckBox chkCertifiedMediator;

        protected global::System.Web.UI.WebControls.CheckBox chkCompletedTraining;

        protected global::System.Web.UI.WebControls.Literal ltExperience;

        protected global::System.Web.UI.WebControls.Literal ltSigned;

        protected global::System.Web.UI.WebControls.Literal ltSubmitted;

        protected global::System.Web.UI.WebControls.Literal ltSubmittedIP;

        protected global::System.Web.UI.WebControls.Repeater rptAttachments;

        protected global::System.Web.UI.WebControls.Literal ltNoAttachments;

        protected global::System.Web.UI.WebControls.TextBox txtStatusNotes;

        protected global::System.Web.UI.WebControls.LinkButton cmdApprove;

        protected global::System.Web.UI.WebControls.LinkButton cmdDeny;

        protected global::System.Web.UI.WebControls.HyperLink lnkCancel;
    }
}
