//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tjc.Modules.Arbitrators.Views
{


    public partial class Settings
    {

        protected global::System.Web.UI.UserControl lblFromEmail;

        protected global::System.Web.UI.WebControls.TextBox txtFromEmail;

        protected global::System.Web.UI.UserControl lblCcEmail;

        protected global::System.Web.UI.WebControls.TextBox txtCcEmail;
    }
}
