using System;
using System.ServiceModel;
using System.ServiceModel.Channels;

namespace tjc.Modules.EmployeeDB.Components.SWN
{
    // =========================================================================
    // STUB: UsersClient proxy + supporting DataContract types for the SWN
    // Users service (https://api.sendwordnow.com/webservices/v3/Users.svc).
    //
    // The real types would normally be generated by Visual Studio's "Add
    // Service Reference" wizard (or svcutil.exe) from the WSDL at
    // D:\websites\Intranet\App_WebReferences\swn\Users.wsdl.exclude.
    //
    // These stubs exist only so Components\SWN\SWNServiceRequests.cs,
    // ClientFactory.cs, and CustomAuthorization.cs COMPILE standalone. All
    // methods on UsersClient throw NotImplementedException.
    //
    // When the real Service Reference is added in Visual Studio:
    //   1. DELETE this file (Components\SWN\UsersClientStub.cs).
    //   2. Remove <Compile Include="Components\SWN\UsersClientStub.cs" />
    //      from EmployeeDB.csproj.
    //   3. The generated proxy will live under Service References/swn/... and
    //      produce a UsersClient type in a namespace such as
    //      tjc.Modules.EmployeeDB.swn. Either align the namespaces or add a
    //      `using swn = tjc.Modules.EmployeeDB.swn;` alias and switch the
    //      SWNServiceRequests call sites to use it.
    //   4. Verify the DataContract type names (ContactDetailRequest,
    //      ObjActionResult, GrpActionContactsReq, GrpCreateReq, GrpUpdReq,
    //      GrpSummary, GrpDetail, ContactPntVoiceType, ContactPntTextMsgType,
    //      ContactPntEmailType, ContactCustomField, ContactCustomFieldDefinition,
    //      ObjActionResult1, etc.) still match the generated code.
    // =========================================================================

    /// <summary>
    /// Stub of the generated SWN Users service proxy.
    /// Real type lives at https://api.sendwordnow.com/webservices/v3/Users.svc.
    /// </summary>
    public partial class UsersClient
    {
        public UsersClient()
        {
        }

        public UsersClient(Binding binding, EndpointAddress remoteAddress)
        {
            // TODO: Wire real SWN UsersClient when Service Reference added in Visual Studio
            Binding = binding;
            RemoteAddress = remoteAddress;
            ChannelFactory = new ChannelFactory<IUsersStub>(binding, remoteAddress);
            ClientCredentials = ChannelFactory.Credentials;
        }

        public Binding Binding { get; private set; }
        public EndpointAddress RemoteAddress { get; private set; }
        public ChannelFactory<IUsersStub> ChannelFactory { get; private set; }
        public System.ServiceModel.Description.ClientCredentials ClientCredentials { get; private set; }

        public ObjActionResult[] CreateContacts(ContactDetailRequest[] contacts)
        {
            throw new NotImplementedException("// TODO: Wire real SWN UsersClient when Service Reference added in Visual Studio");
        }

        public ObjActionResult[] UpdateContact(ContactDetailRequest contact)
        {
            throw new NotImplementedException("// TODO: Wire real SWN UsersClient when Service Reference added in Visual Studio");
        }

        public ObjActionResult[] DeleteContacts(string[] contactIds)
        {
            throw new NotImplementedException("// TODO: Wire real SWN UsersClient when Service Reference added in Visual Studio");
        }

        public bool IsContactInAccount(string contactId)
        {
            throw new NotImplementedException("// TODO: Wire real SWN UsersClient when Service Reference added in Visual Studio");
        }

        public GrpSummary[] GetGroups(bool includeMaster)
        {
            throw new NotImplementedException("// TODO: Wire real SWN UsersClient when Service Reference added in Visual Studio");
        }

        public GrpDetail GetGroupDetail(string groupName)
        {
            throw new NotImplementedException("// TODO: Wire real SWN UsersClient when Service Reference added in Visual Studio");
        }

        public GrpSummary[] GetContactGroups(string contactId)
        {
            throw new NotImplementedException("// TODO: Wire real SWN UsersClient when Service Reference added in Visual Studio");
        }

        public ObjActionResult[] CreateGroup(GrpCreateReq group)
        {
            throw new NotImplementedException("// TODO: Wire real SWN UsersClient when Service Reference added in Visual Studio");
        }

        public ObjActionResult UpdateGroup(GrpUpdReq group)
        {
            throw new NotImplementedException("// TODO: Wire real SWN UsersClient when Service Reference added in Visual Studio");
        }

        public ObjActionResult DeleteGroup(string groupId)
        {
            throw new NotImplementedException("// TODO: Wire real SWN UsersClient when Service Reference added in Visual Studio");
        }

        public ObjActionResult[] ActionContactsGroup(GrpActionContactsReq action)
        {
            throw new NotImplementedException("// TODO: Wire real SWN UsersClient when Service Reference added in Visual Studio");
        }

        public ObjActionResult1[] SetContactCustomFieldsDefinition(ContactCustomFieldDefinition[] defs)
        {
            throw new NotImplementedException("// TODO: Wire real SWN UsersClient when Service Reference added in Visual Studio");
        }

        public void Close()
        {
            // No-op for stub.
        }
    }

    /// <summary>
    /// Minimal service contract interface so ChannelFactory compiles. Replaced
    /// by the svcutil-generated IUsers interface when the real Service
    /// Reference is added.
    /// </summary>
    [ServiceContract]
    public interface IUsersStub
    {
        [OperationContract]
        void EchoAuthenticatedStub();
    }

    // ---------------------------------------------------------------------
    // Placeholder DataContract types. Field names and types mirror what the
    // real generated proxy exposes (derived from the VB source's usage). Once
    // the real proxy is generated, delete these; verify shapes match.
    // ---------------------------------------------------------------------

    public partial class ContactDetailRequest
    {
        public string Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public string Country { get; set; }
        public string PreferredLanguage { get; set; }
        public int TimeZoneId { get; set; }
        public ContactCustomField[] CustomFields { get; set; }
        public ContactDetailContactPointsRequest ContactPointsListRequest { get; set; }
    }

    public partial class ContactDetailContactPointsRequest
    {
        public ContactPntVoiceType[] VoiceContactPoints { get; set; }
        public ContactPntTextMsgType[] TextMessageContactPoints { get; set; }
        public ContactPntEmailType[] EmailContactPoints { get; set; }
    }

    public partial class ContactPntVoiceType
    {
        public string Label { get; set; }
        public string Number { get; set; }
        public string Extension { get; set; }
        public string CountryCode { get; set; }
        public int CascadeOrder { get; set; }
    }

    public partial class ContactPntTextMsgType
    {
        public string Label { get; set; }
        public string Number { get; set; }
        public string Carrier { get; set; }
    }

    public partial class ContactPntEmailType
    {
        public string Label { get; set; }
        public string Address { get; set; }
    }

    public partial class ContactCustomField
    {
        public string Name { get; set; }
        public string Value { get; set; }
    }

    public partial class ContactCustomFieldDefinition
    {
        public string Name { get; set; }
    }

    public partial class ObjActionResult
    {
        public ObjActionResultDetailInfo[] Details { get; set; }
    }

    public partial class ObjActionResult1
    {
        public ObjActionResultDetailInfo[] Details { get; set; }
    }

    public partial class ObjActionResultDetailInfo
    {
        public ObjActionResultDetailInfoType Type { get; set; }
        public string Desc { get; set; }
    }

    public enum ObjActionResultDetailInfoType
    {
        Information = 0,
        Warning = 1,
        Error = 2
    }

    public partial class GrpSummary
    {
        public string Name { get; set; }
        public string Desc { get; set; }
    }

    public partial class GrpDetail
    {
        public string Name { get; set; }
        public string Desc { get; set; }
        public GrpDetailContact[] ContactsList { get; set; }
    }

    public partial class GrpDetailContact
    {
        public string id { get; set; }
    }

    public partial class GrpCreateReq
    {
        public string Name { get; set; }
        public string Desc { get; set; }
    }

    public partial class GrpUpdReq
    {
        public string Name { get; set; }
        public string NewName { get; set; }
        public GrpUpdReqNewDesc NewDesc { get; set; }
    }

    public partial class GrpUpdReqNewDesc
    {
        public bool Clear { get; set; }
        public string Value { get; set; }
    }

    public partial class GrpActionContactsReq
    {
        public GrpActionContactsReqActionType ActionType { get; set; }
        public string GroupName { get; set; }
        public string[] ContactIdsList { get; set; }
    }

    public enum GrpActionContactsReqActionType
    {
        Add = 0,
        Remove = 1
    }
}
