//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tjc.Modules.CDSPAdmin.Views
{
    public partial class SubmissionList
    {
        /// <summary>rptSubmissions control.</summary>
        protected global::System.Web.UI.WebControls.Repeater rptSubmissions;
    }
}
