//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tjc.Modules.JudicialReferral.Views
{
    public partial class Review
    {
        protected global::System.Web.UI.WebControls.Panel pnlJA;
        protected global::System.Web.UI.WebControls.DropDownList drpJudge;
        protected global::System.Web.UI.WebControls.TextBox txtCaseNumber;
        protected global::System.Web.UI.WebControls.TextBox txtCaseParties;
        protected global::System.Web.UI.WebControls.TextBox txtMotionTitle;
        protected global::System.Web.UI.WebControls.TextBox txtMotionDate;
        protected global::System.Web.UI.WebControls.Literal ltAttachments;
        protected global::System.Web.UI.WebControls.Repeater rptFiles;
        protected global::System.Web.UI.WebControls.HiddenField hdIsJudge;

        protected global::System.Web.UI.WebControls.Panel pnlJudge;
        protected global::System.Web.UI.WebControls.RadioButtonList rblDivisions;

        // Criminal
        protected global::System.Web.UI.WebControls.RadioButton chkStatusOrder;
        protected global::System.Web.UI.WebControls.TextBox txtStatusOrderFiled;
        protected global::System.Web.UI.WebControls.CustomValidator valStatusOrderFiled;
        protected global::System.Web.UI.WebControls.RadioButton chkMotionVacate;
        protected global::System.Web.UI.WebControls.RadioButton chkMotionCorrect;
        protected global::System.Web.UI.WebControls.TextBox txtMotionCorrectFiled;
        protected global::System.Web.UI.WebControls.CustomValidator valMotionCorrectFiled;
        protected global::System.Web.UI.WebControls.RadioButton chkMotionDirected;
        protected global::System.Web.UI.WebControls.RadioButtonList clsMotionList;
        protected global::System.Web.UI.WebControls.CustomValidator valMotionDirected;
        protected global::System.Web.UI.WebControls.RadioButton chkOtherPostconviction;
        protected global::System.Web.UI.WebControls.TextBox txtPostconvictionCriminal;
        protected global::System.Web.UI.WebControls.CustomValidator valPostconvictionCriminal;
        protected global::System.Web.UI.WebControls.RadioButton chkPretrialCriminal;
        protected global::System.Web.UI.WebControls.TextBox txtPretrialCriminal;
        protected global::System.Web.UI.WebControls.CustomValidator valPretrialCriminal;
        protected global::System.Web.UI.WebControls.CheckBox chkResearchCriminal;
        protected global::System.Web.UI.WebControls.TextBox txtResearchCriminal;
        protected global::System.Web.UI.WebControls.CustomValidator valResearchCriminal;
        protected global::System.Web.UI.WebControls.CustomValidator valMotionCheckCriminal;

        // Civil
        protected global::System.Web.UI.WebControls.RadioButton chkDismissCivil;
        protected global::System.Web.UI.WebControls.RadioButton chkSummaryJudgementCivil;
        protected global::System.Web.UI.WebControls.RadioButton chkCompelDiscoveryCivil;
        protected global::System.Web.UI.WebControls.RadioButton chkAttorneyFeesCivil;
        protected global::System.Web.UI.WebControls.RadioButton chkPretrialCivil;
        protected global::System.Web.UI.WebControls.TextBox txtPretrialCivil;
        protected global::System.Web.UI.WebControls.CustomValidator valPretrialCivil;
        protected global::System.Web.UI.WebControls.CheckBox chkResearchCivil;
        protected global::System.Web.UI.WebControls.TextBox txtResearchCivil;
        protected global::System.Web.UI.WebControls.CustomValidator valResearchCivil;
        protected global::System.Web.UI.WebControls.CustomValidator valCivilCheck;

        // Family
        protected global::System.Web.UI.WebControls.CheckBox chkModifyTimeshareFamily;
        protected global::System.Web.UI.WebControls.CheckBox chkModifySupportFamily;
        protected global::System.Web.UI.WebControls.CheckBox chkCompelDiscoveryFamily;
        protected global::System.Web.UI.WebControls.CheckBox chkAttorneyFeesFamily;
        protected global::System.Web.UI.WebControls.CheckBox chkPretrialFamily;
        protected global::System.Web.UI.WebControls.TextBox txtPretrialFamily;
        protected global::System.Web.UI.WebControls.CustomValidator valPretrialFamily;
        protected global::System.Web.UI.WebControls.CheckBox chkResearchFamily;
        protected global::System.Web.UI.WebControls.TextBox txtResearchFamily;
        protected global::System.Web.UI.WebControls.CustomValidator valResearchFamily;
        protected global::System.Web.UI.WebControls.CustomValidator valCivilMotionCheck;

        // Appeals
        protected global::System.Web.UI.WebControls.TextBox txtAppeals;
        protected global::System.Web.UI.WebControls.CustomValidator valAppeals;

        // Judicial Response
        protected global::System.Web.UI.WebControls.RadioButton chkNo;
        protected global::System.Web.UI.WebControls.RadioButton chkYes;
        protected global::System.Web.UI.WebControls.RadioButtonList clsResponse;
        protected global::System.Web.UI.WebControls.TextBox txtOther;
        protected global::System.Web.UI.WebControls.CustomValidator valYes;
        protected global::System.Web.UI.WebControls.CustomValidator valOther;
        protected global::System.Web.UI.WebControls.CustomValidator valResponse;
        protected global::System.Web.UI.WebControls.TextBox txtRequestedCompletionDate;
        protected global::System.Web.UI.WebControls.CustomValidator valRequestedCompletionDate;

        // Buttons
        protected global::System.Web.UI.WebControls.LinkButton cmdSave;
        protected global::System.Web.UI.WebControls.LinkButton cmdComplete;
        protected global::System.Web.UI.WebControls.HyperLink cmdCancel;
    }
}
