//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tjc.Modules.ThreatReport
{
    public partial class Settings
    {
        protected global::System.Web.UI.WebControls.Label lblViewerRole;
        protected global::System.Web.UI.WebControls.TextBox txtViewerRole;
        protected global::System.Web.UI.WebControls.Label lblJud12Role;
        protected global::System.Web.UI.WebControls.TextBox txtJud12Role;
    }
}
