//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tjc.Modules.CourtCounsel.Views
{
    public partial class CaseList
    {
        /// <summary>
        /// lnkSearch control.
        /// </summary>
        protected global::System.Web.UI.WebControls.HyperLink lnkSearch;

        /// <summary>
        /// liAdmin control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl liAdmin;

        /// <summary>
        /// rptCaseList control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptCaseList;
    }
}
