//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tjc.Modules.CourtCounsel.Views
{
    public partial class EditHistory
    {
        /// <summary>
        /// liAdmin control.
        /// </summary>
        protected global::System.Web.UI.HtmlControls.HtmlGenericControl liAdmin;

        /// <summary>
        /// valSummary control.
        /// </summary>
        protected global::System.Web.UI.WebControls.ValidationSummary valSummary;

        /// <summary>
        /// txtDateReceived control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtDateReceived;

        /// <summary>
        /// rfvDateReceived control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvDateReceived;

        /// <summary>
        /// txtCaseNumber control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtCaseNumber;

        /// <summary>
        /// rfvCaseNumber control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvCaseNumber;

        /// <summary>
        /// revCaseNumber control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RegularExpressionValidator revCaseNumber;

        /// <summary>
        /// txtCaseName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtCaseName;

        /// <summary>
        /// rfvCaseName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvCaseName;

        /// <summary>
        /// drpCaseType control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList drpCaseType;

        /// <summary>
        /// rfvCaseType control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvCaseType;

        /// <summary>
        /// drpRequestor control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList drpRequestor;

        /// <summary>
        /// rfvRequestor control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvRequestor;

        /// <summary>
        /// drpAttorney control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList drpAttorney;

        /// <summary>
        /// rfvAttorney control.
        /// </summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvAttorney;

        /// <summary>
        /// txtMotionFiled control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtMotionFiled;

        /// <summary>
        /// drpCounty control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList drpCounty;

        /// <summary>
        /// drpAction control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList drpAction;

        /// <summary>
        /// txtDateCompleted control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtDateCompleted;

        /// <summary>
        /// drpTimeSpan control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList drpTimeSpan;

        /// <summary>
        /// drpStatus control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList drpStatus;

        /// <summary>
        /// txtComments control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtComments;

        /// <summary>
        /// pnlFutureAction control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlFutureAction;

        /// <summary>
        /// txtFutureAction control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtFutureAction;

        /// <summary>
        /// cmdSave control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button cmdSave;

        /// <summary>
        /// cmdCancel control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button cmdCancel;

        /// <summary>
        /// cmdDelete control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Button cmdDelete;
    }
}
