//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tjc.Modules.CourtRegistry
{
    public partial class BasicSettings
    {
        protected global::System.Web.UI.WebControls.DropDownList drpMonth;
        protected global::System.Web.UI.WebControls.DropDownList drpDay;
        protected global::System.Web.UI.WebControls.TextBox txtContactEmail;
        protected global::System.Web.UI.WebControls.TextBox txtUpdateNotificationSendTo;
        protected global::System.Web.UI.WebControls.TextBox txtEditAttorneyNote;
        protected global::System.Web.UI.WebControls.TextBox txtEditApplicationNote;
        protected global::System.Web.UI.WebControls.TextBox txtVerificationNote;
        protected global::System.Web.UI.WebControls.TextBox txtApplicationEmail;
        protected global::System.Web.UI.WebControls.Button cmdSave;
        protected global::System.Web.UI.WebControls.HyperLink lnkCancel;
        protected global::System.Web.UI.WebControls.Literal ltMessage;
    }
}
