//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tjc.Modules.CourtRegistry
{
    public partial class CaseTypes
    {
        protected global::System.Web.UI.UpdatePanel pnlCaseTypes;
        protected global::System.Web.UI.WebControls.Literal ltModalScript;
        protected global::System.Web.UI.WebControls.Repeater rptCaseTypes;
        protected global::System.Web.UI.WebControls.HiddenField hdCaseTypeID;
        protected global::System.Web.UI.WebControls.TextBox txtCaseTypeName;
        protected global::System.Web.UI.WebControls.CheckBox chkActive;
        protected global::System.Web.UI.WebControls.Button cmdSave;
    }
}
