//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tjc.Modules.CourtRegistry
{
    public partial class JacCodes
    {
        protected global::System.Web.UI.WebControls.Repeater rptJacCodes;
    }
}
