//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tjc.Modules.EmployeeDB.Views
{

    public partial class Birthdays
    {

        /// <summary>
        /// drpMonth control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList drpMonth;

        /// <summary>
        /// drpCounty control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList drpCounty;

        /// <summary>
        /// cmdReport control.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton cmdReport;

        /// <summary>
        /// rptBirthdays control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptBirthdays;
    }
}
