//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tjc.Modules.EmployeeDB.Views
{

    public partial class DetailPopUp
    {

        /// <summary>
        /// imgPhoto control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Image imgPhoto;

        /// <summary>
        /// ltName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal ltName;

        /// <summary>
        /// ltTitle control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal ltTitle;

        /// <summary>
        /// ltDepartment control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal ltDepartment;

        /// <summary>
        /// ltLocation control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal ltLocation;

        /// <summary>
        /// ltEmail control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Literal ltEmail;

        /// <summary>
        /// rptPhones control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptPhones;

        /// <summary>
        /// pnlNotFound control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Panel pnlNotFound;
    }
}
