//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tjc.Modules.EmployeeDB.Views
{

    public partial class DetailsList
    {

        /// <summary>
        /// rptDetails control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptDetails;
    }
}
