//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tjc.Modules.EmployeeDB.Views
{

    public partial class Directory
    {

        /// <summary>
        /// txtFirstName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtFirstName;

        /// <summary>
        /// txtLastName control.
        /// </summary>
        protected global::System.Web.UI.WebControls.TextBox txtLastName;

        /// <summary>
        /// drpDepartment control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList drpDepartment;

        /// <summary>
        /// drpCounty control.
        /// </summary>
        protected global::System.Web.UI.WebControls.DropDownList drpCounty;

        /// <summary>
        /// cmdSearch control.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton cmdSearch;

        /// <summary>
        /// cmdReset control.
        /// </summary>
        protected global::System.Web.UI.WebControls.LinkButton cmdReset;

        /// <summary>
        /// rptDirectory control.
        /// </summary>
        protected global::System.Web.UI.WebControls.Repeater rptDirectory;
    }
}
