//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tjc.Modules.EmployeeDB.Views
{
    public partial class EditEmployee
    {
        /// <summary>lblEmployeeName control.</summary>
        protected global::System.Web.UI.WebControls.Label lblEmployeeName;

        /// <summary>valSummary control.</summary>
        protected global::System.Web.UI.WebControls.ValidationSummary valSummary;

        /// <summary>ltMessage control.</summary>
        protected global::System.Web.UI.WebControls.Literal ltMessage;

        // ===== Details Tab =====
        /// <summary>txtFirstName control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtFirstName;
        /// <summary>rfvFirstName control.</summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvFirstName;

        /// <summary>txtLastName control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtLastName;
        /// <summary>rfvLastName control.</summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvLastName;

        /// <summary>txtMiddleInitial control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtMiddleInitial;

        /// <summary>txtJobTitle control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtJobTitle;

        /// <summary>txtSsn control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtSsn;
        /// <summary>rfvSsn control.</summary>
        protected global::System.Web.UI.WebControls.RequiredFieldValidator rfvSsn;

        /// <summary>txtBirthDate control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtBirthDate;

        /// <summary>drpRace control.</summary>
        protected global::System.Web.UI.WebControls.DropDownList drpRace;

        /// <summary>drpGender control.</summary>
        protected global::System.Web.UI.WebControls.DropDownList drpGender;

        /// <summary>drpAgency control.</summary>
        protected global::System.Web.UI.WebControls.DropDownList drpAgency;

        /// <summary>txtAddress control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtAddress;
        /// <summary>txtCity control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtCity;
        /// <summary>txtState control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtState;
        /// <summary>txtZip control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtZip;
        /// <summary>drpCounty control.</summary>
        protected global::System.Web.UI.WebControls.DropDownList drpCounty;

        /// <summary>txtEmail control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtEmail;
        /// <summary>revEmail control.</summary>
        protected global::System.Web.UI.WebControls.RegularExpressionValidator revEmail;

        /// <summary>txtPersonalEmail control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtPersonalEmail;
        /// <summary>revPersonalEmail control.</summary>
        protected global::System.Web.UI.WebControls.RegularExpressionValidator revPersonalEmail;

        /// <summary>drpOfficeLocation control.</summary>
        protected global::System.Web.UI.WebControls.DropDownList drpOfficeLocation;
        /// <summary>txtLocationName control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtLocationName;

        /// <summary>drpSupervisor control.</summary>
        protected global::System.Web.UI.WebControls.DropDownList drpSupervisor;
        /// <summary>drpDepartment control.</summary>
        protected global::System.Web.UI.WebControls.DropDownList drpDepartment;
        /// <summary>drpJobGroup control.</summary>
        protected global::System.Web.UI.WebControls.DropDownList drpJobGroup;
        /// <summary>drpClass control.</summary>
        protected global::System.Web.UI.WebControls.DropDownList drpClass;

        /// <summary>txtPosition control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtPosition;
        /// <summary>drpEmploymentType control.</summary>
        protected global::System.Web.UI.WebControls.DropDownList drpEmploymentType;
        /// <summary>txtSalary control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtSalary;

        /// <summary>txtHireDate control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtHireDate;
        /// <summary>txtServiceDate control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtServiceDate;
        /// <summary>txtTerminationDate control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtTerminationDate;

        /// <summary>txtAnnualLeave control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtAnnualLeave;
        /// <summary>txtSickLeave control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtSickLeave;
        /// <summary>txtBadgeNumber control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtBadgeNumber;
        /// <summary>txtSwnGroupId control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtSwnGroupId;

        /// <summary>lblUserId control.</summary>
        protected global::System.Web.UI.WebControls.Label lblUserId;
        /// <summary>cmdAssociateUser control.</summary>
        protected global::System.Web.UI.WebControls.LinkButton cmdAssociateUser;

        /// <summary>chkIsActive control.</summary>
        protected global::System.Web.UI.WebControls.CheckBox chkIsActive;
        /// <summary>chkIsEmployee control.</summary>
        protected global::System.Web.UI.WebControls.CheckBox chkIsEmployee;

        /// <summary>pnlSelectUser control.</summary>
        protected global::System.Web.UI.WebControls.Panel pnlSelectUser;
        /// <summary>txtSelectUserId control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtSelectUserId;
        /// <summary>cmdSelectUserSave control.</summary>
        protected global::System.Web.UI.WebControls.LinkButton cmdSelectUserSave;
        /// <summary>cmdSelectUserCancel control.</summary>
        protected global::System.Web.UI.WebControls.LinkButton cmdSelectUserCancel;

        // ===== Groups Tab =====
        /// <summary>lstGroups control.</summary>
        protected global::System.Web.UI.WebControls.ListBox lstGroups;
        /// <summary>cmdSaveGroups control.</summary>
        protected global::System.Web.UI.WebControls.LinkButton cmdSaveGroups;

        // ===== Employment History Tab =====
        /// <summary>rptPositionHistory control.</summary>
        protected global::System.Web.UI.WebControls.Repeater rptPositionHistory;
        /// <summary>txtPosStartDate control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtPosStartDate;
        /// <summary>txtPosEndDate control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtPosEndDate;
        /// <summary>txtPosEntryType control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtPosEntryType;
        /// <summary>chkPosInternal control.</summary>
        protected global::System.Web.UI.WebControls.CheckBox chkPosInternal;
        /// <summary>txtPosDescription control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtPosDescription;
        /// <summary>cmdAddPosition control.</summary>
        protected global::System.Web.UI.WebControls.LinkButton cmdAddPosition;

        /// <summary>rptServiceHistory control.</summary>
        protected global::System.Web.UI.WebControls.Repeater rptServiceHistory;
        /// <summary>txtSvcCompanyName control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtSvcCompanyName;
        /// <summary>txtSvcHireDate control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtSvcHireDate;
        /// <summary>txtSvcTerminationDate control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtSvcTerminationDate;
        /// <summary>txtSvcLastPayRate control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtSvcLastPayRate;
        /// <summary>cmdAddService control.</summary>
        protected global::System.Web.UI.WebControls.LinkButton cmdAddService;

        // ===== Phones Tab =====
        /// <summary>rptPhones control.</summary>
        protected global::System.Web.UI.WebControls.Repeater rptPhones;
        /// <summary>drpPhoneType control.</summary>
        protected global::System.Web.UI.WebControls.DropDownList drpPhoneType;
        /// <summary>txtPhoneNumber control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtPhoneNumber;
        /// <summary>txtPhoneExtension control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtPhoneExtension;
        /// <summary>chkPhoneIsMain control.</summary>
        protected global::System.Web.UI.WebControls.CheckBox chkPhoneIsMain;
        /// <summary>chkPhoneSwnCall control.</summary>
        protected global::System.Web.UI.WebControls.CheckBox chkPhoneSwnCall;
        /// <summary>chkPhoneSwnText control.</summary>
        protected global::System.Web.UI.WebControls.CheckBox chkPhoneSwnText;
        /// <summary>chkPhoneSwnExcludeExt control.</summary>
        protected global::System.Web.UI.WebControls.CheckBox chkPhoneSwnExcludeExt;
        /// <summary>cmdAddPhone control.</summary>
        protected global::System.Web.UI.WebControls.LinkButton cmdAddPhone;

        // ===== Emergency Contacts Tab =====
        /// <summary>rptContacts control.</summary>
        protected global::System.Web.UI.WebControls.Repeater rptContacts;
        /// <summary>txtContactFirstName control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtContactFirstName;
        /// <summary>txtContactLastName control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtContactLastName;
        /// <summary>txtContactRelationship control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtContactRelationship;
        /// <summary>txtContactCallOrder control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtContactCallOrder;
        /// <summary>txtContactPhoneHome control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtContactPhoneHome;
        /// <summary>txtContactPhoneWork control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtContactPhoneWork;
        /// <summary>txtContactPhoneMobile control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtContactPhoneMobile;
        /// <summary>cmdAddContact control.</summary>
        protected global::System.Web.UI.WebControls.LinkButton cmdAddContact;

        // ===== Access Cards Tab =====
        /// <summary>chkManateeAccess control.</summary>
        protected global::System.Web.UI.WebControls.CheckBox chkManateeAccess;
        /// <summary>txtSarasotaAccess control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtSarasotaAccess;
        /// <summary>txtDesotoAccess control.</summary>
        protected global::System.Web.UI.WebControls.TextBox txtDesotoAccess;

        // ===== Photo Tab =====
        /// <summary>imgPhoto control.</summary>
        protected global::System.Web.UI.WebControls.Image imgPhoto;
        /// <summary>hdnPhotoFileId control.</summary>
        protected global::System.Web.UI.WebControls.HiddenField hdnPhotoFileId;
        /// <summary>fuPhoto control.</summary>
        protected global::System.Web.UI.WebControls.FileUpload fuPhoto;

        // ===== Footer Buttons =====
        /// <summary>cmdSave control.</summary>
        protected global::System.Web.UI.WebControls.LinkButton cmdSave;
        /// <summary>cmdDelete control.</summary>
        protected global::System.Web.UI.WebControls.LinkButton cmdDelete;
        /// <summary>cmdCancel control.</summary>
        protected global::System.Web.UI.WebControls.HyperLink cmdCancel;
    }
}
