//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tjc.Modules.EmployeeDB.Views
{
    public partial class NewHireITWorksheet
    {
        // The .ascx is composed entirely of plain HTML + AJAX, so there
        // are no asp:* server controls to declare here. The designer file
        // exists to satisfy the standard Web Forms partial-class pairing
        // expected by msbuild + Visual Studio's code-behind generator.
    }
}
